# Generated by Django 4.2.18 on 2025-03-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Ціна'),
        ),
    ]
